config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/users/worktime/new', to: 'worktimes#new', as: 'intime'
  post '/users/worktime/update', to: 'worktimes#update', as: 'outtime'
  get  '/users/:id', to: "users#entry", as: 'entry'
  post '/users/:id/history', to: 'worktimes#list', as: 'list'
  get '/users/:id/history', to: 'worktimes#history', as: 'history'
  resources :users, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :must_data, presence: true
  validates :limited_data, presence: true, length: {minimum: 10, maximum: 100 }
  validates :address_number, presence: true, format: { with: /\A[0-9]{7}\z/}


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/models/worktime.rb
class Worktime < ApplicationRecord
  def self.list(user_id,month,year)
    where(user_id: user_id, month: month, year: year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      remember user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or entry_path(current_user)
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
    else
      # flash[:danger] = 'Invalid email/password combination' # 本当は正しくない
      flash.now[:danger] = 'Invalid email/password combination'
      # エラーメッセージを作成する
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:list, :edit, :update, :destroy, :entry]
  before_action :correct_user,   only: [:edit, :update, :entry]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def entry
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "会員登録完了"
      redirect_to entry_path(current_user)
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # beforeアクション

  # ログイン済みユーザーかどうか確認
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/controllers/worktimes_controller.rb
require 'date'
class WorktimesController < ApplicationController
  def history
  end

  def list
    @works = Worktime.list(session[:user_id], params[:worktime][:month], params[:worktime][:year])
    @month = params[:worktime][:month]
      #binding.pry
  end

  def entry
  end

  def new
    #lastがnilの時の処理を書こう
    last_worktime = Worktime.find_by(user_id: session[:user_id],
                                    year: Time.now.strftime("%Y"),
                                    month: Time.now.strftime("%m"),
                                    day: Time.now.strftime("%d"))
    #@last_worktime.nil?
    if last_worktime.nil?
      worktime = Worktime.new(user_id: session[:user_id],
                               in_time: Time.now,
                               year: Time.now.strftime("%Y"),
                               month: Time.now.strftime("%m"),
                               day: Time.now.strftime("%d"))
      worktime.save
      flash[:success] = '出勤時間を登録しました'
      redirect_to entry_path(current_user)
    else
      flash[:notice] = 'すでに本日分は登録済みです'
      redirect_to entry_path(current_user)
    end

    # 書き込み条件
    # user_idがsession[:user_id]かつ年月日がTime.nowと同じデータがない場合
    #
  end

  def update
    #binding.pry
    worktime = Worktime.find_by(user_id: session[:user_id],
                               year: Time.now.strftime("%Y"),
                               month: Time.now.strftime("%m"),
                               day: Time.now.strftime("%d"))
    if worktime.nil?
      flash[:fail] = '先に出勤してください'
      redirect_to current_user
    elsif worktime.out_time.nil?
      worktime.out_time = Time.now
      worktime.save
      flash[:success] = '退勤時間を登録しました。お疲れさまでした'
      redirect_to entry_path(current_user)
    else
      flash[:notice] = 'すでに本日分は登録済みです'
      redirect_to entry_path(current_user)
    end
    # 書き込み条件
    # find（user_id: current_user.id）したデータのout_timeがnil



  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "勤怠管理システム"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # セッションハッシュのuser_idキーに入れる
  def log_in(user)
    session[:user_id] = user.id
  end

  # クッキーからuserIDとトークンを読み出す
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #ブラウザを閉じていた場合でも自動でログインする処理をクッキーを用いて実装
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  #ユーザーがログイン前にアクセスしようとしていたページにログイン後にとばす
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  #ユーザーが変わっていないか確認
  def current_user?(user)
    user == current_user
  end
  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end
  # クッキーからトークンを削除
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  # クッキーからトークンを削除した後セッションを終了（sessionのuserIDを削除）
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/worktimes_helper.rb
module WorktimesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">


</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "研修用勤怠管理システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Menu <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "勤怠打刻", entry_path(current_user) %></li>
              <li><%= link_to "出勤記録一覧", history_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application',
                             'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>

    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>

  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>

</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a> and
  <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>  Get help on the Ruby on Rails Tutorial at the
  <a href="https://railstutorial.jp/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em>
    book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>勤怠管理システム</h1>

  <h2>
    利用には会員登録が必要です
  </h2>
  <% if logged_in? %>
    <%= link_to "マイページ", entry_path(current_user), class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= link_to "会員登録", signup_path, class: "btn btn-lg btn-primary" %>
    <%= "または" %>
    <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.label "入力必須" %>
  <%= f.text_field :must_data, class: 'form-control' %>

  <%= f.label "10~100文字" %>
  <%= f.text_field :limited_data, class: 'form-control' %>

  <%= f.label "郵便番号（数字７桁）" %>
  <%= f.text_field :address_number, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% content_for(:title, "edit user") %>
<% provide(:url, user_path) %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/entry.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1 align="center">
        <%= gravatar_for @user %>
        <%= "ようこそ#{@user.name}さん" %>
        <%="現在時刻は" %><br>
        <%="#{Time.zone.now}です"%>
        <%= button_to "出勤", url: intime_path, controller: "worktimes",action: "new"%>
        <%= button_to "退勤", url: outtime_path, controller: "worktimes",action: "update"%>
      </h1>
    </section>
  </aside>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render @users %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<% provide(:url, signup_path) %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/worktimes/history.html.erb
<% provide(:title, '月別勤務一覧') %>
<%=form_for(:worktime,url: list_path) do |f|%>
  <%= f.select :month, [["1"], ["2"], ["3"], ["4"], ["5"], ["6"], ["7"], ["8"], ["9"], ["10"], ["11"], ["12"]], :selected=>Time.zone.now.month%>
  <%= f.select :year,  (Time.zone.now.year - 10)..(Time.zone.now.year), :selected=>Time.zone.now.year%>
  <%=f.submit "検索"%>

<% end %>

app/views/worktimes/list.html.erb
<% provide(:title, '月別勤務一覧') %>
<h1>月別勤務一覧</h1>
<%="指定された年月の勤務記録はありません" if @works.empty? %>


<table border="5" align="center">
  <tr>
    <th>勤務日</th>
    <th>出勤時間</th>
    <th>退勤時間</th>
    <th>勤務時間</th>
  </tr>
  <% @works.each do |work| %>
    <tr>
      <td><%= work.in_time.strftime("%Y年%m月%d日") %></td>
      <td><%= work.in_time.strftime("%I:%M %p") %></td>
      <td><%= work.out_time.present? ? work.out_time.strftime("%I:%M %p") : work.out_time %></td>
      <td><%= work.out_time.present? ? Time.at(work.out_time - work.in_time).utc.strftime('%X') : "退勤してください"%></td>
    </tr>
  <% end %>
  </table>